return {}
-- return {
--   {
--     "SmiteshP/nvim-navic",
--     -- dir = "~/src/nvim-navic",
--     event = { "BufReadPost", "BufNewFile" },
--     config = function()
--       local navic = require("nvim-navic")

--       navic.setup {
--         highlight = true,
--         safe_output = true,
--         click = true,
--       }
--     end,
--   },
--   {
--     "SmiteshP/nvim-navbuddy",
--     dependencies = {
--         "neovim/nvim-lspconfig",
--         "SmiteshP/nvim-navic",
--         "MunifTanjim/nui.nvim",
--         "numToStr/Comment.nvim",        -- Optional
--         "nvim-telescope/telescope.nvim" -- Optional
--     },
--     config = function()
--       local navbuddy = require("nvim-navbuddy")
--       require("lspconfig").clangd.setup {
--           on_attach = function(client, bufnr)
--               navbuddy.attach(client, bufnr)
--           end
--       }
--     end
--   }
-- }
